### ISSUE TITLE
chore: replace ghcr references with DockerHub

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger#10]
See [TRG](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05). Please replace the docker image links to the DockerHub ones. References with ghcr.io I've found:

- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/charts/simpledataexchanger/README.md?plain=1#L31
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/charts/simpledataexchanger/README.md?plain=1#L69
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/charts/simpledataexchanger/values.yaml#L38
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/charts/simpledataexchanger/values.yaml#L190

**Comment by almadigabor** [comment]
@adityagajbhiye9 I still see the ghcr.io references in the links of the description.

**Comment by adityagajbhiye9** [comment]
Removed the ghrc reference image.
