### ISSUE TITLE
chore: add missing license headers in chart

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger#11]
See [TRG](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02#chart-file-structure). Please add missing license header to these files:

- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/charts/chart-testing-config.yaml
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/charts/simpledataexchanger/templates/_helpers.tpl

**Comment by adityagajbhiye9** [comment]
License header added.
