### ISSUE TITLE
values.yaml should not set insecure default passwords

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger#22]
Creating this issue regarding hard-coded passwords in the values.yaml:

In Line [29](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/50083abadab0da43aa23752f4377786a4a9f8b9c/charts/simpledataexchanger/values.yaml#L29) and [31](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/50083abadab0da43aa23752f4377786a4a9f8b9c/charts/simpledataexchanger/values.yaml#L31) the postgres passwords are set to "default", please consider using the the [bitmami default](https://github.com/bitnami/charts/blob/6ec633ba194236430b35957024e242b4373c5e58/bitnami/postgresql/values.schema.json#L43) and let helm generate random passwords by setting the strings to "".

**Comment by hzierer** [comment]
@adityagajbhiye9 can you please have a look?

**Comment by adityagajbhiye9** [comment]
Sure. Updating.

**Comment by hzierer** [comment]
Can you also fix line [31](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/50083abadab0da43aa23752f4377786a4a9f8b9c/charts/simpledataexchanger/values.yaml#L31)?

The bitnami chart generates random passwords for both: [password](https://github.com/bitnami/charts/blob/6ec633ba194236430b35957024e242b4373c5e58/bitnami/postgresql/values.schema.json#L43) and [postgresPassword](https://github.com/bitnami/charts/blob/6ec633ba194236430b35957024e242b4373c5e58/bitnami/postgresql/values.schema.json#L25)

**Comment by adityagajbhiye9** [comment]
> Can you also fix line [31](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/50083abadab0da43aa23752f4377786a4a9f8b9c/charts/simpledataexchanger/values.yaml#L31)?
> 
> The bitnami chart generates random passwords for both: [password](https://github.com/bitnami/charts/blob/6ec633ba194236430b35957024e242b4373c5e58/bitnami/postgresql/values.schema.json#L43) and [postgresPassword](https://github.com/bitnami/charts/blob/6ec633ba194236430b35957024e242b4373c5e58/bitnami/postgresql/values.schema.json#L25)

I have removed the postgresPassword, but for password it is required quote, 
(Values.sdepostgresql.auth.password is required | quote) for running . It is use for managed service SDE. 
I am checking with randon password generation.

**Comment by adityagajbhiye9** [comment]
working on it.

**Comment by adityagajbhiye9** [comment]
Successfully  auto generated  password  created.

**Comment by hzierer** [comment]
fixed with https://github.com/eclipse-tractusx/managed-simple-data-exchanger/pull/25
