### ISSUE TITLE
[TRG 1.01] appropriate README.md

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger#35]
Hi,
as stated in [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1/) "... a good README is a crucial component of any repository, serving as a gateway for users and contributors to understand, use, and potentially contribute to your project..."

Could you please add to the `README.md`s of all 3 repos a short description what SDE is/does. Only a few sentences at the beginning. This would help new users a lot.

**Comment by adityagajbhiye9** [comment]
@hzierer  #36  PR raised.
