### ISSUE TITLE
TRG 8.04 Mitigate high and above findings in Trivy

### ISSUE THREAD

**Issue by RoKrish14** [eclipse-tractusx/managed-simple-data-exchanger#53]
Trivy has reported 6 High findings and 1 High finding under [managed-simple-data-exchanger-frontend](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend) and  [managed-simple-data-exchanger-backend](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend) respectively. Please take necessary action and provide resolution for the findings.

**Comment by adityagajbhiye9** [comment]
Mitigated the finding
