### ISSUE TITLE
TRG 5.09 Helm Test running properly

### ISSUE THREAD

**Issue by RoKrish14** [eclipse-tractusx/managed-simple-data-exchanger#54]
Release-Helm Charts fails in [managed-simple-data-exchanger-backend](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend).

Cause: uses: helm/chart-releaser-action@v1.4.6
Solution: uses: helm/chart-releaser-action@v1.6.0

**Comment by adityagajbhiye9** [comment]
@RoKrish14  As we have leading repo.This chart release will be depreciated.

**Comment by adityagajbhiye9** [comment]
Can we close this issue?
