### ISSUE TITLE
TRG 1.01 appropriate `README.md`

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger#7]
See [TRG1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1)

Missing parts of the [readme](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/blob/main/README.md):

- A description on what the application does
- How to configure the application or link to application configuration description.

**Comment by adityagajbhiye9** [comment]
Corrected the readme file.
