### ISSUE TITLE
docs: add docs folder with proper content

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger#8]
See [TRG](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3#docs). `The /docs directory must contain detailed product related documentation for the Tractus-X product. Folder structure inside this directory is the responsibility of the repository owner/product team.`

**Comment by adityagajbhiye9** [comment]
docs folder added.

**Comment by almadigabor** [comment]
please reference this file in your README.md as well so people can find it
